version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=magento
      - MYSQL_ROOT_PASSWORD=root
    restart: always
    volumes: 
      - ./db:/var/lib/mysql
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db
    ports:
      - 443:80
    environment:
      - PMA_ARBITRARY=1

  php-apache:
    build: .
    volumes:
       - ./:/var/www/html/
       - "./dockerfiles/config/php.ini-development:/usr/local/etc/php/php.ini-development"
       - "./dockerfiles/config/php.ini-production:/usr/local/etc/php/php.ini-production"
    ports:
       - 5000:80
    links:
       - db