<div class="container-fluid" style="text-align: center;">
    <img src="http://192.168.0.241:5000/magento2/pub/media/img/motor.JPG" usemap="#image_map">
    <map name="image_map">
        <area alt="Pistão" title="Pistão" data-toggle="modal" and data-target="#pistao" coords="375,17,415,28"
            shape="rect">
        <area alt="Embreagem" title="Embreagem" data-toggle="modal" and data-target="#embreagem"
            coords="312,167,381,176" shape="rect">
        <area alt="Cambio" title="Cambio" data-toggle="modal" and data-target="#cambio" coords="224,79,266,88"
            shape="rect">
        <area alt="Rodado" title="Rodado" data-toggle="modal" and data-target="#rodado" coords="200,265,246,275"
            shape="rect">
        <area alt="Diferencial" title="Diferencial" data-toggle="modal" and data-target="#diferencial"
            coords="118,84,188,93" shape="rect">
        <area alt="TDP" title="TDP" data-toggle="modal" and data-target="#tdp" coords="19,200,40,212" shape="rect">
        <area alt="Redutor" title="Redutor" data-toggle="modal" and data-target="#redutor" coords="67,251,117,261"
            shape="rect">
    </map>
</div>

<!-- Modal -->
<div id="pistao" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                <h2>Pistão</h2>
                <p>O melhor pistão do mercado...</p>
                <a class="btn btn-primary" href="http://192.168.0.241:5000/magento2/pistao.html">Comprar</a>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
            </div>
        </div>

    </div>
</div>

<div id="embreagem" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                <h2>Embreagem</h2>
                <p>Some text in the modal.</p>
                <a class="btn btn-primary" href="http://192.168.0.241:5000/magento2/pistao.html">Comprar</a>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
            </div>
        </div>

    </div>
</div>

<div id="cambio" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                <h2>Cambio</h2>
                <p>Some text in the modal.</p>
                <a class="btn btn-primary" href="http://192.168.0.241:5000/magento2/pistao.html">Comprar</a>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
            </div>
        </div>

    </div>
</div>

<div id="rodado" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                <h2>Rodado</h2>
                <p>Some text in the modal.</p>
                <a class="btn btn-primary" href="http://192.168.0.241:5000/magento2/pistao.html">Comprar</a>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
            </div>
        </div>

    </div>
</div>

<div id="diferencial" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                <h2>Diferencial</h2>
                <p>Some text in the modal.</p>
                <a class="btn btn-primary" href="http://192.168.0.241:5000/magento2/pistao.html">Comprar</a>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
            </div>
        </div>

    </div>
</div>

<div id="tdp" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                <h2>TDP</h2>
                <p>Some text in the modal.</p>
                <a class="btn btn-primary" href="http://192.168.0.241:5000/magento2/pistao.html">Comprar</a>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
            </div>
        </div>

    </div>
</div>

<div id="redutor" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                <h2>Redutor</h2>
                <p>Some text in the modal.</p>
                <a class="btn btn-primary" href="http://192.168.0.241:5000/magento2/pistao.html">Comprar</a>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
            </div>
        </div>

    </div>
</div>

<!-- Optional JavaScript -->
<script type="text/javascript">
require(['bootstrap']);
</script>
