<style>
#imagem {
    position: relative;
    margin-top: 0;
}

#Enviar {
    display: none;
}
</style>
<?php
$url = $this->getUrl('diagramas/index/index', ['_secure'=> true]);
?>

<div id="imagem" style="text-align: center;">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <img id="uploadPreview" />
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <form id="upload" action="<?=$url?>" method="POST" enctype="multipart/form-data">
                    <input id="uploadImage" type="file" class="form-control-file" name="myPhoto"
                        onchange="PreviewImage();" />
                </form>
                    <!--<button id="Enviar" class="btn btn-primary">Salvar Imagem</button>
                    <button id="novo" class="btn btn-primary">Novo Diagrama</button>-->
            </div>
        </div>
    </div>
</div>

</br>

<script type="text/javascript">
//novo.addEventListener('click', () => atualizaPagina());
function PreviewImage() {
    let imagem = document.getElementById("uploadImage");
    //let enviar = document.getElementById('Enviar');
    var oFReader = new FileReader();
    oFReader.readAsDataURL(imagem.files[0]);
    oFReader.onload = function(oFREvent) {
        document.getElementById("uploadPreview").src = oFREvent.target.result;
        imagem.style.display = 'none';
        //enviar.style.display = 'block';
    };
};

require(['jquery', 'jquery/ui'], function($) {

    var form = $("#upload")[0];
    //var enviar = $("#Enviar");

    $("#uploadImage").on("change", function(event) {
        var data = new FormData(form);
        $.ajax({
            url: form.action,
            data: data,
            contentType: false,
            processData: false,
            type: form.method,
            success: function(data) {
                console.log(data);
            }
        });
        return false;
    });
});
</script>

<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->create('\Magento\Store\Model\StoreManagerInterface');
$baseURL_l = $social_image_url = $storeManager->getStore()->getBaseUrl();
$url = $baseURL_l."diagramas/index/index";
?>
