<?php
/**
 * @var $block \Engepecas\Diagramas\Block\Adminhtml\Index\Index
 */

$bloco = $block->getLayout()->createBlock('Engepecas\Diagramas\Block\Adminhtml\Index\Index');
$upload_bloco = $block->getLayout()->createBlock('Engepecas\Diagramas\Block\Adminhtml\Index\Booking');

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->create('\Magento\Store\Model\StoreManagerInterface');
$baseURL_l = $social_image_url = $storeManager->getStore()->getBaseUrl();
$caminho = $baseURL_l.'pub/media/img/';
?>
<style>
    .selecionado{
        position: absolute;
        background: #FAB600;
        border-radius: 100%;
        border: 1px #000 solid;
        width: 2em;
        height: 2em;
        text-align: center;
        font-size: 1em;
    }
    #selecao {
        position: absolute;
        display: none;
        background: #FAB600;
        border-radius: 100%;
        border: 1px #000 solid;
        width: 2em;
        height: 2em;
    }

    .selecao:before {
        content: ' ';
    }

    #salva {
        display: none;
    }

    #imagem {
        position: relative;
        display: flex;
    }

    #Enviar {
        display: none;
    }

    #uploadPreview {
        width: auto;
        height: max-content;
    }

    .page-header{
        margin-top: 0 !important;
        padding: 0 3rem !important;
    }
    #description{
        margin-top: 0 !important;
        padding: 0 0 0 !important;
    }

    form .form_ {
        font-size: 1.5em;
    }

    .small {
        font-size: 1.5em;
    }
    .codigo, .botoes{
        display: none;
    }

</style>
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<?php
$url = $this->getUrl('diagramas/index/index', ['_secure'=> true]);
?>
</main>

<div class="row">
    <div id="imagem" class="col" style="margin-left: 30px">
        <img id="uploadPreview" />
        <div id="selecao"></div>
        <div id="selecionado"></div>
    </div>
    <div class="col-6">
        <div id="tabela"> </div>
    </div>
</div>
<main id="anchor-content" class="page-content">

</br>
<?php
$img = '';
$img_tmp = '';
$img_cam = "http://192.168.0.241:5000/magento2/pub/media/img/";
$motor_diagrama = $bloco->getIdMotorDiagrama();
$url = $this->getUrl('diagramas/index/index', ['_secure'=> true]);

?>

<div class="row">
        <div class="col-md-4">
            <form id="upload" action="<?=$url?>" method="POST" enctype="multipart/form-data" style="font-size: 1.5em;">
                <div class="form-row">
                    <div class="form-group col-md-12">
                        <input id="uploadImage" type="file" class="custom-file-input" name="myPhoto" onchange="PreviewImage();" />
                        <label id="label1" class="custom-file-label">Escolha uma Imagem</label>
                    </div>
                </div>
            </form>
        </div>
        <div class="col-md-8">
            <form action="<?=$url?>">
                <div class="form-row">
                    <div class="form-group col-md-4">
                        <select class="form-control form_" id="id_prod">
                            <?php
                                echo "<option  value='null'>Escolha um Motor</option>";
                            foreach($motor_diagrama as $value){
                                $id = $value['entity_id'];
                                $valor = $value['VALUE'];
                                echo "<option  value='$id'>$valor</option>";
                            }
                            ?>
                        </select>
                    </div>
                    <div class="form-group col-md-4 codigo">
                        <input type="text" class="form-control form_" placeholder="CODIGO DA PEÇA (SKU)" name="sku" id="sku">
                    </div>
                    <div class="form-group">
                        <input type="hidden" class="form-control" name="titulo" id="titulo">
                        <input type="hidden" class="form-control" name="id" id="id">
                        <input type="hidden" class="form-control" name="link" id="link">
                        <input type="hidden" class="form-control" name="price" id="price">
                        <input type="hidden" class="form-control" name="entity_id" id="entity_id">
                    </div>
                    <div class="form-group col-md-4 botoes">
                        <button type="button" class="action- scalable action-secondary add" id="add">Adicionar</button>
                        <button type="button" class="action-default primary" id="slv">Salvar</button>
                    </div>
                </div>
            </form>
        </div>
</div>
<div class="row">
    <div class="col-12">
        <form action="<?=$url?>" method="POST" id="upload">
            <div id="info">
            </div>
            <button type="submit" id="salva" class="btn btn-primary text-white">Salvar</button>
        </form>
    </div>
</div>

<!-- Optional JavaScript -->
<script>

let img_cam = document.querySelector('#uploadImage');
let sku = document.getElementById('sku');
let id_prod = document.getElementById('id_prod');
let img_motor;
let tr;
let div;
let left_;
let top_;
let left_b;
let top_b;
let qtd_sele;


function PreviewImage() {
    let imagem = document.getElementById("uploadImage");
    var oFReader = new FileReader();
    oFReader.readAsDataURL(imagem.files[0]);
    oFReader.onload = function(oFREvent) {
        document.getElementById("uploadPreview").src = oFREvent.target.result;
        document.getElementById("label1").innerHTML = 'Alterar Imagem';
    };
};

require(['jquery', 'jquery/ui'], function($) {

    var form = $("#upload")[0];

    $("#uploadImage").on("change", function(event) {
        var data = new FormData(form);
        $.ajax({
            url: form.action,
            data: data,
            contentType: false,
            processData: false,
            type: form.method,
            success: function(data) {
                console.log(data);
                img_motor = data;
            }
        });
        return false;
    });
});

/*** seleciona area da imagem e pega as coordenadas */
let img = document.getElementById('uploadPreview');
let selecao = document.getElementById('selecao');
let selecionado = document.getElementById('selecionado');

img.addEventListener('mousedown', function(e) {
    var rect = e.target.getBoundingClientRect();
    inicio = {
        x: e.pageX,
        y: e.pageY
    };
    inicio.x = inicio.x - rect.left;
    inicio.y = inicio.y - 141; //rect.top;
    var altura = document.getElementById('uploadPreview').offsetHeight;
    var largura = document.getElementById('uploadPreview').offsetWidth;
    left_ = (inicio.x * 100 / largura);
    top_ = (inicio.y * 100 / altura);
    left_b = inicio.x;
    top_b = inicio.y;
    selecao.style.display = 'block';
    selecao.style.left = inicio.x+ 'px';
    selecao.style.top = inicio.y + 'px';
});

let pos;
require(['jquery', 'jquery/ui'], function($) {
    var url_prod = $("#link");
    $('#add').on('click', function(e) {
        if(img_motor === undefined){
            img_motor = $('#uploadPreview').attr('src');
        }
        pos = selecao.getBoundingClientRect();
        var entity_id_motor_ =  id_prod.value;
        right = pos.right;
        bottom = pos.bottom;
        var valor_sku = sku.value;/**Código sku da peça */
        $.ajax({
            type: 'post',
            url: url_prod,
            data: {
                entity_id_motor: `${entity_id_motor_}`,
                sku: `${valor_sku}`,
                left: `${left_}`,
                top: `${top_}`,
                left_b: `${left_b}`,
                top_b: `${top_b}`,
                mt_img: `${img_motor}`
            },
            error: function() {
                alert('Erro ao tentar ação!');
            },
            success: function(retorno) {
                var json = JSON.parse(retorno);
                var x = 0;
                tr = '';
                div = '';
                while(x < json.length){
                    tr += `
                        <tr>
                            <th><img src="${json[x].imagem}" style="width: 100px"></th>
                            <th>${json[x].sku}</th>
                            <th>${json[x].value}</th>
                            <th>${json[x].request_path}</th>
                            <th>${json[x].price}</th>
                            <th><button type="button" class="btn btn-dark" onclick="DeleteProd(${json[x].diagrama_id});">Remover</button></th>
                        </tr>
                    `;
                    div += `<div class="selecionado" id="${x}" style="left: ${json[x].left_b}px; top: ${json[x].top_b}px; font-size: 1em;">${x+1}</div>`;
                    x++;
                    qtd_sele = x;
                }
                gerarTabela(tr);
            }
        });
    });

    $('#id_prod').on('change', function(){
        $.ajax({
            type: 'post',
            url: url_prod,
            data: {
                entity_id_motor: `${id_prod.value}`
            },
            error: function() {
                alert('Erro ao tentar ação!');
            },
            success: function(retorno) {
                var json = JSON.parse(retorno);
                var x = 0;
                tr = '';
                div = '';
                while(x < json.length){
                    if(json[x].mt_img != ''){
                        $('#uploadPreview').attr('src', json[x].mt_img);
                    }
                    tr += `
                        <tr>
                            <th><img src="${json[x].imagem}" style="width: 100px"></th>
                            <th>${json[x].sku}</th>
                            <th>${json[x].value}</th>
                            <th>${json[x].request_path}</th>
                            <th>${json[x].price}</th>
                            <th><button type="button" class="btn btn-dark" onclick="DeleteProd('${json[x].diagrama_id}',);">Remover</button></th>
                        </tr>
                    `;
                    div += `<div class="selecionado" id="${x}" style="left: ${json[x].left_b}px; top: ${json[x].top_b}px; font-size: 1em;">${x+1}</div>`;
                    x++;
                    qtd_sele = x;
                }
                if(id_prod.value != 'null'){
                    document.getElementById("label1").innerHTML = 'Alterar Imagem';
                    document.querySelector(".codigo").style.display = 'block';
                    document.querySelector(".botoes").style.display = 'block';
                }else{
                    document.querySelector(".codigo").style.display = 'none';
                    document.querySelector(".botoes").style.display = 'none';
                }
                gerarTabela(tr);
            }
        });
    });

    $('#slv').on('click', function(){

        if(img_motor === undefined){
            img_motor = $('#uploadPreview').attr('src');
        }
        var url_prod = $("#link");
        var id_motor_ =  id_prod.value;
        var file_ = img_motor;
        $.ajax({
            type: 'post',
            url: url_prod,
            data: {
                id_motor: `${id_motor_}`,
                file_url: `${file_}`
            },
            error: function() {
                alert('Erro ao tentar ação!');
            },
            success: function(retorno) {
                console.log(retorno);
            }
        });
    });
});

function DeleteProd(id){
    require(['jquery', 'jquery/ui'], function($) {
        var entity_id_motor_ =  id_prod.value;
        var url_prod = $("#link");
        $.ajax({
            type: 'post',
            url: url_prod,
            data: {
                deletar: 'true',
                entity_id_motor: `${entity_id_motor_}`,
                id: `${id}`
            },
            error: function(){

            },
            success: function(retorno){
                var json = JSON.parse(retorno);
                var x = 0;
                tr = '';
                div = '';
                while(x < json.length){
                    tr += `
                        <tr>
                            <th><img src="${json[x].imagem}" style="width: 100px"></th>
                            <th>${json[x].sku}</th>
                            <th>${json[x].value}</th>
                            <th>${json[x].request_path}</th>
                            <th>${json[x].price}</th>
                            <th><button type="button" class="btn btn-dark" onclick="DeleteProd('${json[x].diagrama_id}',);">Remover</button></th>
                        </tr>
                    `;
                    div += `<div class="selecionado" id="${x}" style="left: ${json[x].left_b}px; top: ${json[x].top_b}px; font-size: 1em;">${x+1}</div>`;
                    x++;
                    qtd_sele = x;
                }
                gerarTabela(tr);
            }
        });
    });
}

function gerarTabela(tr){
    let tabela = document.getElementById('tabela');
    var tabela_texto = `
    <table class="table">
        <thead class="thead-dark">
            <tr>
            <th scope="col">Miniatura</th>
            <th scope="col">SKU</th>
            <th scope="col">Nome</th>
            <th scope="col">URL</th>
            <th scope="col">Preço</th>
            <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            ${tr}
        </tbody>
    </table>
    `;
    selecionado.innerHTML = div;
    tabela.innerHTML = tabela_texto;
}

</script>
