<style>
#imagem {
    position: relative;
    margin-top: 0;
}

#Enviar {
    display: none;
}

<?php print_r($_REQUEST);
//$url=$this->getUrl('admin/diagramas/index/index', ['_secure'=> true]);
$url=$this->getUrl('admin/diagramas/upload/upload', ['_secure'=> true]);
?>
</style>

<div id="imagem" style="text-align: center;">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <img id="uploadPreview" />
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <!--$this->getUrl('admin/diagramas/index/index', ['_secure' => true]);-->
                <!--<form id="upload" action="/upload.php" method="POST" enctype="multipart/form-data">-->
                <form id="upload" action="<?=$url?>" method="POST" enctype="multipart/form-data">
                    <input id="uploadImage" type="file" class="form-control-file" name="myPhoto"
                        onchange="PreviewImage();" />
                    <button id="Enviar" class="btn btn-primary" type="submit">Salvar Imagem</button>
                </form>
            </div>
        </div>
    </div>
</div>

</br>

<script type="text/javascript">
function PreviewImage() {
    let imagem = document.getElementById("uploadImage");
    let enviar = document.getElementById('Enviar');
    var oFReader = new FileReader();
    oFReader.readAsDataURL(imagem.files[0]);
    oFReader.onload = function(oFREvent) {
        document.getElementById("uploadPreview").src = oFREvent.target.result;
        imagem.style.display = 'none';
        enviar.style.display = 'block';
    };
};

require(['jquery', 'jquery/ui'], function($) {

    var form = $("#upload")[0];
    var enviar = $("#Enviar");
    enviar.on("click", function(event) {
        var data = new FormData(form);
        $.ajax({
            url: form.action,
            data: data,
            contentType: false,
            processData: false,
            type: form.method,
            success: function(data) {
                console.log(data);
            }
        });
        return false;
    });
});
</script>

<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->create('\Magento\Store\Model\StoreManagerInterface');
$baseURL_l = $social_image_url = $storeManager->getStore()->getBaseUrl();
$url = $baseURL_l."diagramas/index/index";
?>
